service: auth-server

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1
    timeout: 30
    environment:
        CLIENT_ID: ${file(config.json):CLIENT_ID}
        CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
        CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
    getAuthURL:
        handler: handler.getAuthURL
        events:
            - http:
                  path: api/get-auth-url
                  method: get
    # getAccessToken:
    # Passes auth code from getAuthURL
    # Gets token from Google
    # getCalendarEvents:
    # Send GET request with token
    # Google returns data
